# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.8 on 2016-12-13 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 1.9 on 2016-12-07 08:56
from __future__ import unicode_literals

from django.db import migrations, models
>>>>>>> jomy


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('numOfSpeakers', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Diarization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Speaker_id', models.IntegerField()),
                ('Diarization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irapp.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Summary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irapp.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='TextGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('TextGraph_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irapp.Audio')),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> jomy
            name='User',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irapp.User'),
        ),
=======
                ('password', models.CharField(max_length=100)),
            ],
        ),
>>>>>>> jomy
    ]
