# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import irapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.FileField(upload_to='audio')),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to=irapp.models.get_upload_to)),
                ('sentimentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irapp.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to=irapp.models.get_upload_to)),
                ('summaryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irapp.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irapp.User'),
        ),
    ]
