# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('numOfSpeakers', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Diarization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Speaker_id', models.IntegerField()),
                ('Diarization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irapp.Audio')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='audio',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irapp.User'),
        ),
    ]
