# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irapp', '0002_auto_20161213_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.ImageField(upload_to='audio'),
        ),
    ]
