# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irapp', '0003_auto_20161213_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.FileField(upload_to='audio'),
        ),
    ]
