# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irapp', '0004_auto_20161213_1418'),
        ('irapp', '0004_auto_20161213_1358'),
    ]

    operations = [
    ]
